# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: database
    restart: always
    ports:
    - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  pgdata: {}