services:
  api:
    image: tiagodreadd/todo-api
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      GIN_MODE: debug
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: tiagodreadd/todo-db
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    networks:
      - todo-network

volumes:
  pgdata: {}

networks:
  todo-network:
    driver: bridge
