services:
  api:
    image: tiagodreadd/todo-api:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/postgres?sslmode=disable
      GIN_MODE: release
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: tiagodreadd/todo-db:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - todo-network

volumes:
  pgdata: {}

networks:
  todo-network:
    driver: bridge
