FROM postgres

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=postgres

# Executing SQL file on startup
RUN chmod 777 -R /docker-entrypoint-initdb.d/
COPY initdb.sql /docker-entrypoint-initdb.d/